name: 🐛 Bug Report
description: Report a bug to help us improve ViberCode CLI
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment
      value: |
        - OS: [e.g. macOS 13.5, Ubuntu 22.04, Windows 11]
        - Go version: [e.g. 1.21.0]
        - ViberCode CLI version: [e.g. v1.0.0]
        - Node.js version (if using vibe mode): [e.g. v18.17.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: If applicable, add logs or error messages
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
